/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPublicationRegistry,
  IPublicationRegistryInterface,
} from "../../../contracts/ValidationRegistry.sol/IPublicationRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
    ],
    name: "getPublication",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "author",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "timestamp",
            type: "uint96",
          },
          {
            internalType: "bool",
            name: "exists",
            type: "bool",
          },
        ],
        internalType: "struct IPublicationRegistry.Publication",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPublicationRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPublicationRegistryInterface {
    return new Interface(_abi) as IPublicationRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPublicationRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPublicationRegistry;
  }
}
