/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputationSystem,
  IReputationSystemInterface,
} from "../../../contracts/ValidationRegistry.sol/IReputationSystem";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
    ],
    name: "canValidate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "decreaseReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "increaseReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReputationSystem__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationSystemInterface {
    return new Interface(_abi) as IReputationSystemInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReputationSystem {
    return new Contract(address, _abi, runner) as unknown as IReputationSystem;
  }
}
