/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as validationRegistrySol from "./ValidationRegistry.sol";
export type { validationRegistrySol };
export type { PublicationRegistry } from "./PublicationRegistry";
export type { ReputationSystem } from "./ReputationSystem";
