/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PublicationRegistry } from "./PublicationRegistry";
export * as factories from "./factories";
export { PublicationRegistry__factory } from "./factories/PublicationRegistry__factory";
