/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPublicationRegistry } from "./IPublicationRegistry";
export type { IReputationSystem } from "./IReputationSystem";
export type { ValidationRegistry } from "./ValidationRegistry";
