/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPublicationRegistry {
  export type PublicationStruct = {
    author: AddressLike;
    timestamp: BigNumberish;
    exists: boolean;
  };

  export type PublicationStructOutput = [
    author: string,
    timestamp: bigint,
    exists: boolean
  ] & { author: string; timestamp: bigint; exists: boolean };
}

export interface IPublicationRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getPublication"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPublication",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPublication",
    data: BytesLike
  ): Result;
}

export interface IPublicationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPublicationRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPublicationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPublication: TypedContractMethod<
    [contentHash: BytesLike],
    [IPublicationRegistry.PublicationStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPublication"
  ): TypedContractMethod<
    [contentHash: BytesLike],
    [IPublicationRegistry.PublicationStructOutput],
    "view"
  >;

  filters: {};
}
