/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ValidationRegistry {
  export type ValidationStruct = { validator: AddressLike; vote: BigNumberish };

  export type ValidationStructOutput = [validator: string, vote: bigint] & {
    validator: string;
    vote: bigint;
  };
}

export interface ValidationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "consensusReached"
      | "consensusResult"
      | "getValidations"
      | "quorumThreshold"
      | "reputationSystem"
      | "submitValidation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ConsensusReached" | "ValidationSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "consensusReached",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "consensusResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quorumThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationSystem",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitValidation",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "consensusReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consensusResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quorumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitValidation",
    data: BytesLike
  ): Result;
}

export namespace ConsensusReachedEvent {
  export type InputTuple = [contentHash: BytesLike, result: BigNumberish];
  export type OutputTuple = [contentHash: string, result: bigint];
  export interface OutputObject {
    contentHash: string;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationSubmittedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    validator: AddressLike,
    vote: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    validator: string,
    vote: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    validator: string;
    vote: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValidationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ValidationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ValidationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consensusReached: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  consensusResult: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getValidations: TypedContractMethod<
    [contentHash: BytesLike],
    [ValidationRegistry.ValidationStructOutput[]],
    "view"
  >;

  quorumThreshold: TypedContractMethod<[], [bigint], "view">;

  reputationSystem: TypedContractMethod<[], [string], "view">;

  submitValidation: TypedContractMethod<
    [contentHash: BytesLike, vote: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consensusReached"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "consensusResult"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidations"
  ): TypedContractMethod<
    [contentHash: BytesLike],
    [ValidationRegistry.ValidationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "quorumThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reputationSystem"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitValidation"
  ): TypedContractMethod<
    [contentHash: BytesLike, vote: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConsensusReached"
  ): TypedContractEvent<
    ConsensusReachedEvent.InputTuple,
    ConsensusReachedEvent.OutputTuple,
    ConsensusReachedEvent.OutputObject
  >;
  getEvent(
    key: "ValidationSubmitted"
  ): TypedContractEvent<
    ValidationSubmittedEvent.InputTuple,
    ValidationSubmittedEvent.OutputTuple,
    ValidationSubmittedEvent.OutputObject
  >;

  filters: {
    "ConsensusReached(bytes32,uint8)": TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;
    ConsensusReached: TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;

    "ValidationSubmitted(bytes32,address,uint8)": TypedContractEvent<
      ValidationSubmittedEvent.InputTuple,
      ValidationSubmittedEvent.OutputTuple,
      ValidationSubmittedEvent.OutputObject
    >;
    ValidationSubmitted: TypedContractEvent<
      ValidationSubmittedEvent.InputTuple,
      ValidationSubmittedEvent.OutputTuple,
      ValidationSubmittedEvent.OutputObject
    >;
  };
}
