/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as validationRegistrySol from "./ValidationRegistry.sol";
export { PublicationRegistry__factory } from "./PublicationRegistry__factory";
export { ReputationSystem__factory } from "./ReputationSystem__factory";
