/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  PublicationRegistry,
  PublicationRegistryInterface,
} from "../../contracts/PublicationRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
    ],
    name: "PublicationAlreadyExists",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
    ],
    name: "PublicationNotFound",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "author",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PublicationRegistered",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
    ],
    name: "getPublication",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "author",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "timestamp",
            type: "uint96",
          },
          {
            internalType: "bool",
            name: "exists",
            type: "bool",
          },
        ],
        internalType: "struct PublicationRegistry.Publication",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "publications",
    outputs: [
      {
        internalType: "address",
        name: "author",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "timestamp",
        type: "uint96",
      },
      {
        internalType: "bool",
        name: "exists",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
    ],
    name: "registerPublication",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102ea806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063131b948d146100465780633a697ff71461009457806345df7dae146100a9575b600080fd5b61005961005436600461029b565b61011e565b6040805182516001600160a01b031681526020808401516001600160601b031690820152918101511515908201526060015b60405180910390f35b6100a76100a236600461029b565b6101c2565b005b6100ef6100b736600461029b565b600060208190529081526040902080546001909101546001600160a01b03821691600160a01b90046001600160601b03169060ff1683565b604080516001600160a01b0390941684526001600160601b03909216602084015215159082015260600161008b565b6040805160608101825260008082526020808301829052828401829052848252819052919091206001015460ff1661017157604051630f750ab360e01b8152600481018390526024015b60405180910390fd5b5060009081526020818152604091829020825160608101845281546001600160a01b0381168252600160a01b90046001600160601b0316928101929092526001015460ff1615159181019190915290565b60008181526020819052604090206001015460ff16156101f85760405163a60c1d6360e01b815260048101829052602401610168565b60408051606081018252338082526001600160601b03428181166020808601828152600187890181815260008b81528085528a902098519251909616600160a01b026001600160a01b03909216919091178755935195909301805495151560ff19909616959095179094559351928352909184917f53507eda96388a0136a0470da8f2cd9517159f4cf4f8b371b661b3c42ba9e4f2910160405180910390a35050565b6000602082840312156102ad57600080fd5b503591905056fea2646970667358221220cd7c5833f407f9a062d8651ae7fa7af71fae575948119c56b9a472c8b87674b764736f6c63430008140033";

type PublicationRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PublicationRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PublicationRegistry__factory extends ContractFactory {
  constructor(...args: PublicationRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PublicationRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): PublicationRegistry__factory {
    return super.connect(runner) as PublicationRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PublicationRegistryInterface {
    return new Interface(_abi) as PublicationRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PublicationRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as PublicationRegistry;
  }
}
